version: '3.8'

services:

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: apicontrol
      MYSQL_PASSWORD: apicontrol
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ibcs_db